fluvigestWebApp/config/routes.rb
FluvigestWebApp::Application.routes.draw do
  resources :tarifas

  resources :linea_facturas
  resources :facturas do
    resources :linea_facturas
  end
  resources :facturas

  root 'facturas#index'

  

end

fluvigestWebApp/app/models/factura.rb
class Factura < ActiveRecord::Base
  has_many :linea_facturas, dependent: :destroy
end

fluvigestWebApp/app/models/linea_factura.rb
class LineaFactura < ActiveRecord::Base
  belongs_to :factura
end

fluvigestWebApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

fluvigestWebApp/app/controllers/facturas_controller.rb
class FacturasController < ApplicationController
  before_action :set_factura, only: [:show, :edit, :update, :destroy]

  # GET /facturas
  # GET /facturas.json
  def index
    @facturas = Factura.all
  end

  # GET /facturas/1
  # GET /facturas/1.json
  def show
  end

  # GET /facturas/new
  def new
    @factura = Factura.new
  end

  # GET /facturas/1/edit
  def edit
  end

  # POST /facturas
  # POST /facturas.json
  def create
    @factura = Factura.new(factura_params)

    respond_to do |format|
      if @factura.save
        format.html { redirect_to facturas_path }
        format.json { render action: 'show', status: :created, location: @factura }
      else
        format.html { render action: 'new' }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facturas/1
  # PATCH/PUT /facturas/1.json
  def update
    respond_to do |format|
      if @factura.update(factura_params)
        format.html { redirect_to facturas_path}
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facturas/1
  # DELETE /facturas/1.json
  def destroy
    @factura.destroy
    respond_to do |format|
      format.html { redirect_to facturas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_factura
      @factura = Factura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def factura_params
      params.require(:factura).permit(:descripcion, :fecha)
    end
end

fluvigestWebApp/app/controllers/linea_facturas_controller.rb
class LineaFacturasController < ApplicationController
  before_action :set_linea_factura, only: [:show, :edit, :update, :destroy]

  # GET /linea_facturas
  # GET /linea_facturas.json
  def index
    #@factura = Factura.find(params[:factura_id])
    @linea_facturas = LineaFactura.all
  end

  # GET /linea_facturas/1
  # GET /linea_facturas/1.json
  def show

  end

  # GET /linea_facturas/new
  def new
    @factura = Factura.find(params[:factura_id])
    session[:id_factura] = @factura.id
    @linea_factura = LineaFactura.new
  end

  # GET /linea_facturas/1/edit
  def edit
  end

  # POST /linea_facturas
  # POST /linea_facturas.json
  def create

    @factura = Factura.find(session[:id_factura])
    @linea_factura = @factura.linea_facturas.create(params[:linea_factura].permit(:numero, :descripcion))
    redirect_to factura_path(@factura)

    #@linea_factura = LineaFactura.new(linea_factura_params)

    #respond_to do |format|
     # if @linea_factura.save
      #  format.html { redirect_to @linea_factura, notice: 'Linea factura was successfully created.' }
       # format.json { render action: 'show', status: :created, location: @linea_factura }
      #else
       # format.html { render action: 'new' }
       # format.json { render json: @linea_factura.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # PATCH/PUT /linea_facturas/1
  # PATCH/PUT /linea_facturas/1.json
  def update
    #@factura = Factura.find(params[:factura_id])
    #@linea_factura = @factura.linea_facturas.find(params[:id])
    #@linea_factura.update(params[:linea_factura].permit(:numero, :descripcion))
    @factura = Factura.find(@linea_factura.factura)
    @linea_factura.update(linea_factura_params)
    redirect_to factura_path(@factura)
    #respond_to do |format|
      #if @linea_factura.update(linea_factura_params)
       # format.html { redirect_to linea_factura_path }
       # format.json { head :no_content }
      #else
      #  format.html { render action: 'edit' }
      #  format.json { render json: @linea_factura.errors, status: :unprocessable_entity }
     # end
    #end
  end

  def verLineas

  end

  # DELETE /linea_facturas/1
  # DELETE /linea_facturas/1.json
  def destroy
    @factura = Factura.find(params[:factura_id])
    @linea_factura = @factura.linea_facturas.find(params[:id])
    @linea_factura.destroy
    redirect_to factura_path(@factura)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_linea_factura
      @linea_factura = LineaFactura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def linea_factura_params
      params.require(:linea_factura).permit(:factura_id, :numero, :descripcion)
    end
end

fluvigestWebApp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

fluvigestWebApp/app/helpers/application_helper.rb
module ApplicationHelper
end

fluvigestWebApp/app/helpers/facturas_helper.rb
module FacturasHelper
end

fluvigestWebApp/app/helpers/linea_facturas_helper.rb
module LineaFacturasHelper
end

fluvigestWebApp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

fluvigestWebApp/app/views/facturas/_form.html.erb
<%= form_for(@factura) do |f| %>
  <% if @factura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@factura.errors.count, "error") %> prohibited this factura from being saved:</h2>

      <ul>
      <% @factura.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.datetime_select :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

fluvigestWebApp/app/views/facturas/edit.html.erb
<h1>Editing factura</h1>

<%= render 'form' %>

<%= link_to 'Back', facturas_path %>

fluvigestWebApp/app/views/facturas/index.html.erb
<h1>LISTA DE FACTURAS</h1>
<div class="CSSTableGenerator">
<table>

    <tr>
      <td>Descripcion</td>
      <td>Fecha</td>
      <td></td>
      <td></td>
      <td></td>
    </tr>



    <% @facturas.each do |factura| %>
      <tr>
        <td><%= factura.descripcion %></td>
        <td><%= factura.fecha %></td>
        <td><%= link_to 'Mostrar', factura %></td>
        <td><%= link_to 'Editar', edit_factura_path(factura) %></td>
        <td><%= link_to 'Borrar', factura, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>

</table>
</div>
<br>

<%= link_to 'Crear factura', new_factura_path %>

fluvigestWebApp/app/views/facturas/new.html.erb
<h1>New factura</h1>

<%= render 'form' %>

<%= link_to 'Back', facturas_path %>

fluvigestWebApp/app/views/facturas/show.html.erb
<p id="notice"><%= notice %></p>
<h1>LINEAS DE FACTURA</h1>
<div class="CSSTableGenerator">
  <table>
    <tr>
      <td>Numero</td>
      <td>Descripcion</td>
      <td></td>
      <td></td>
    </tr>
    <% @factura.linea_facturas.each do |linea_factura| %>
        <tr>
          <td><%= linea_factura.numero %></td>
          <td><%= linea_factura.descripcion %></td>
          <td><%= link_to 'Editar', edit_linea_factura_path(linea_factura) %></td>
          <td><%= link_to 'Eliminar', [linea_factura.factura, linea_factura],
                      method: :delete,
                      data: { confirm: '¿Estas seguro?' } %>   </td>
        </tr>
    <% end %>
  </table>
</div>
<%= link_to 'Añadir linea', new_factura_linea_factura_path(@factura.id) %>
<%= link_to 'Back', facturas_path %>

fluvigestWebApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FluvigestWebApp</title>
  <%= stylesheet_link_tag "tablaFactura.css" %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

fluvigestWebApp/app/views/linea_facturas/_form.html.erb
<%= form_for(@linea_factura) do |f| %>
  <% if @linea_factura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@linea_factura.errors.count, "error") %> prohibited this linea_factura from being saved:</h2>

      <ul>
      <% @linea_factura.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

fluvigestWebApp/app/views/linea_facturas/edit.html.erb
<h1>Editing linea_factura</h1>

<%= render 'form' %>

<%= link_to 'Show', @linea_factura %> |
<%= link_to 'Back', linea_facturas_path %>

fluvigestWebApp/app/views/linea_facturas/index.html.erb
<h1>LINEAS DE FACTURA</h1>
<div class="CSSTableGenerator">
<table>
    <tr>
      <td>Numero</td>
      <td>Descripcion</td>
      <td></td>
      <td></td>
    </tr>
    <% @factura.linea_facturas.each do |linea_factura| %>
      <tr>
        <td><%= linea_factura.numero %></td>
        <td><%= linea_factura.descripcion %></td>
        <td><%= link_to 'Edit', edit_linea_factura_path(linea_factura) %></td>
        <td><%= link_to 'Destroy', linea_factura, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>
</div>
<br>

<%= link_to 'Back', facturas_path %>

fluvigestWebApp/app/views/linea_facturas/new.html.erb
<h1>New linea_factura</h1>

<%= render 'form' %>

<%= link_to 'Back', facturas_path %>

fluvigestWebApp/app/views/linea_facturas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Factura:</strong>
  <%= @linea_factura.factura %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @linea_factura.numero %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @linea_factura.descripcion %>
</p>

<%= link_to 'Edit', edit_linea_factura_path(@linea_factura) %> |
<%= link_to 'Back', linea_facturas_path %>

fluvigestWebApp/app/views/welcome/index.html.erb
<h1>Bienvenido a la aplicación de prueba de Jose</h1>
<%= link_to 'Pincha aquí para ver las facturas disponibles',  %>